### PR TITLE
initial structure for project

### PR DESCRIPTION
**Pull request by bloges56**

### CODE REVIEW

**Review by ember-parr — APPROVED** [review]
looks reactey to me

**Comment by Patchrik** [comment]
I'd delete the old.readme.md before we merge.

**Review by cArel116 — APPROVED** [review]
Solid, brotha!

**Review by Patchrik — CHANGES_REQUESTED** [review]
I'd go ahead and delete the old.readme.md then we're good.

**Review by Patchrik — APPROVED** [review]

**Review by corneliajohnson — APPROVED** [review]

**Pull request merged**
